# -*- coding: utf-8 -*-
"""
/***************************************************************************
 N200DocCreator
                                 A QGIS plugin
 Plugin serves for creating data according to "Standard to collect spatial data for Plans of Protective Actions on Natura 2000 sites", export them, and create maps based on them.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Emil Kielar
        email                : kielaremil@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load N200DocCreator class from file N200DocCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .n_doc_creator import N200DocCreator
    return N200DocCreator(iface)
